### ISSUE TITLE
Errors with pyqtgraph

### ISSUE THREAD

**Issue by gary-harlow** [gary-harlow/HESXRD-Analysis-Toolkit#3]
Cannot initialize filter fcidecomp: File not found
qt5ct: using qt5ct plugin
Traceback (most recent call last):
  File "main.py", line 43, in <module>
    ex = interface.Ram()
  File "/home/giuseppe/HESXRD-Analysis-Toolkit/interface.py", line 39, in __init__
    self.initUI()
  File "/home/giuseppe/HESXRD-Analysis-Toolkit/interface.py", line 714, in initUI
    self.qRegion=pg.LinearRegionItem(orientation='horizontal')
  File "/usr/lib/python3/dist-packages/pyqtgraph/graphicsItems/LinearRegionItem.py", line 66, in __init__
    raise Exception('Orientation must be one of LinearRegionItem.Vertical or LinearRegionItem.Horizontal')
Exception: Orientation must be one of LinearRegionItem.Vertical or LinearRegionItem.Horizontal

or 

self.p.param('Crystal', 'a₁').setValue(2.885)
                                                 ^
SyntaxError: Non-ASCII character '\xe2' in file /home/giuseppe/HESXRD-Analysis-Toolkit/interface.py on line 406, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

**Comment by gary-harlow** [comment]
This is a problem with having an older version of pyqtgraph, in linux please try to run:

pip3 install --user --upgrade pip
pip3 install --user --upgrade pyqtgraph
